bursaries:
  SKE: £175
  veteran:
    full-amount: £40,000
    installment-amount: £20,000
## implemented above this line
  undergraduate: £9,000
  postgraduate:
    chemistry: £28,000
    computing: £28,000
    maths: £28,000
    physics: £28,000
    biology: £25,000
    design-and-technology: £25,000
    languages-french-german-spanish: £25,000
    languages-all-others-including-ancient: £25,000
    languages-funding-widget: £25,000
    geography: £25,000
    art-and-design: £10,000
    english: £10,000
    music: £10,000
    religious-education: £10,000
    non-uk-languages-physics: £28,000


