bursaries:
  skeweekly: £175
  veteran:
    total: £40,000
    annual: £20,000
  undergraduate: £9,000
  postgraduate:
    artanddesign: £10,000
    biology: £26,000
    chemistry: £29,000
    computing: £29,000
    designandtechnology: £26,000
    english: £5,000
    geography: £26,000
    languagesfrenchgermanspanish: £26,000
    languagesother: £26,000
    maths: £29,000
    music: £10,000
    nonuk: £29,000
    physics: £29,000
    religiouseducation: £10,000
    nonuk: £29,000
  fundingdates: between September 2025 and July 2026
