bursaries:
  SKE-weekly: £175
  veteran:
    total: £40,000
    instalment: £20,000
## implemented above this line
  postgraduate:
    art-and-design: £10,000
    biology: £25,000
    chemistry: £28,000
    computing: £28,000
    design-and-technology: £25,000
    english: £10,000
    geography: £25,000
    languages-french-german-spanish: £25,000
    languages-funding-widget: £25,000
    languages-other: £25,000
    maths: £28,000
    music: £10,000
    physics: £28,000
    religious-education: £10,000
    non-uk: £28,000
  undergraduate: £9,000


