bursaries:
  skeweekly: £175
  veteran:
    total: £40,000
    annual: £20,000
  undergraduate: £9,000
  fundingdates: between September 2026 and July 2027
  postgraduate:
    biology: £5,000
    chemistry: £29,000
    computing: £29,000
    designandtechnology: £20,000
    geography: £5,000
    languagesfrenchgermanspanish: £20,000
    languagesother: £20,000
    maths: £29,000
    physics: £29,000
  2026:
    postgraduate:
      biology: £5,000
      chemistry:
        relevant: £20,000
        unrelated: £10,000
      computing:
        relevant: £20,000
        unrelated: £10,000
      design_technology:
        relevant: £20,000
        unrelated: £10,000
      geography: £5,000
      languages_french_german_spanish: £15,000
      languages_other: £15,000
      maths:
        relevant: £20,000
        unrelated: £10,000
      music: £5,000
      physics:
        relevant: £20,000
        unrelated: £10,000
      religious_education: £5,000
