bursaries:
  skeweekly: £175
  veteran:
    total: £40,000
    annual: £20,000
  undergraduate: £9,000
  postgraduate:
    artanddesign: £10,000
    biology: £25,000
    chemistry: £28,000
    computing: £28,000
    designandtechnology: £25,000
    english: £10,000
    geography: £25,000
    languagesfrenchgermanspanish: £25,000
    languagesother: £25,000
    maths: £28,000
    music: £10,000
    physics: £28,000
    religiouseducation: £10,000
    nonuk: £28,000
