earlyyears:

  bursaries:
    eybursarywithfirstclass: £5,000
    eybursarywithtwoone: £4,000
    eybursarywithtwotwo: £2,000

  fees:
    eycoursefeescoveredbydfe: £7,000
    eycoursefeesselffundedlow: £2,500
    eycoursefeesselffundedhigh: £3,000
    eycoursefeesundergrad: £9,250
