  earlyyears:
    bursarywithfirstclassdegree: £5,000
    bursarywithtwoone: £4,000
    bursarywithtwotwo: £2,000
    coursefeescoveredbydfe: £7,000
    coursefeesselffundedlow: £2,500
    coursefeesselffundedhigh: £3,000