earlyyears:
  
  bursaries:
    withfirstclass: £5,000
    withtwoone: £4,000
    withtwotwo: £2,000

  fees:
    coveredbydfe: £7,000
    selffundedlow: £2,500
    selffundedhigh: £3,000
    undergrad: £9,250
