misc:
  adultdependantsgrant:
    value: £3,438
    incomethreshold: £15,621.98
  ## implemented above this line
  childcaregrantweeklypayment:
    onechild: £193.62
    twoormorechildren: £331.95
  disabilityadditionalfunding: £26,948
  earlyyears:
    bursarywithfirstclassdegree: £5,000
    bursarywithtwoone: £4,000
    bursarywithtwotwo: £2,000
    coursefeescoveredbydfe: £7,000
    coursefeesselffundedlow: £2,500
    coursefeesselffundedhigh: £3,000
  highpotentialindividualvisaminimumsavings: £1,270
  indiayoungprofessionalsschememinimumsavings: £2,530
  internationalrelocationpayment:
    value: £10,000
    instalment: £5,000
    salarythresholdfortaxonpayments: £50,270
  maintenanceloanpaymentvalue:
    liveathomewithparents: £8,610
    awayfromparentsoutsidelondon: £10,227
    awayfromparentsinsidelondon: £13,348
    oversixty: £4,327
  parentslearningallowance:
    lowpayment: £50
    maxpayment: £1,963
    incomethreshold: £18,835.98
  statementofcomparabilitycost: £49.50 plus VAT
  teachinginternshipweekly: £300


