misc:
  ## implemented above this line
  adult-dependants-grant:
    value: £3,438
    income-threshold: £15,621.98
  childcare-grant-weekly-payment:
    one-child: £193.62
    two-or-more-children: £331.95
  disability-additional-funding: £26,948
  early-years:
    bursary-with-first-class-degree: £5,000
    bursary-with-two-one: £4,000
    bursary-with-two-two: £2,000
    course-fees-covered-by-dfe: £7,000
    course-fees-self-funded-low: £2,500
    course-fees-self-funded-high: £3,000
  international-relocation-payment:
    value: £10,000
    instalment: £5,000
    salary-threshold-for-tax-on-payments: £50,270
  maintenance-loan-payment-value:
    live-at-home-with-parents: £8,610
    away-from-parents-outside-london: £10,227
    away-from-parents-inside-london: £13,348
    over-sixty: £4,327
  parents-learning-allowance:
    low-payment: £50
    max-payment: £1,963
    income-threshold: £18,835.98
  statement-of-comparability-cost: £49.50 plus VAT
  teaching-internship-weekly: £300



