## implemented above this line
nonuk:
  internationalrelocationpayment:
    value: £10,000
    instalment: £5,000
    salarythresholdfortaxonpayments: £50,270
  statementofcomparabilitycost: £49.50 + VAT
