nonuk:
  highpotentialindividualvisaminimumsavings: £1,270
  indiayoungprofessionalsschememinimumsavings: £2,530
  internationalrelocationpayment:
    value: £10,000
    instalment: £5,000
    salarythresholdfortaxonpayments: £50,270