nonuk:
# IRP
  internationalrelocationpayment:
    value: £10,000
    instalment: £5,000
    thresholdfortaxonpayments: £50,270
# Statement of comparability  
  statementofcomparabilitycost: £49.50 + VAT
# Visa salary thresholds
  skilledworkervisatraineeminfulltime:
    innerlondon: £25,831
    outerlondon: £24,415
    londonfringe: £23,200
    restofengland: £23,200
  skilledworkervisatraineeminparttime: £23,200
  skilledworkervisateacherminparttime: £23,200
