recruitmentcycle:
  coursestart: September 2026
  openanddeadline: from 9am on 7 October 2025 to 6pm on 21 September 2026
  openingdate: 7 October 2025
  openingmonth: October
  deadlinedate: 21 September 2026
  deadlinetime: 6pm
  providerdeadline: 3 October 2026
  