recruitmentcycle:
  coursestart: September 2025
  openanddeadline: from 9am on 8 October 2024 to 6pm on 16 September 2025
  openingdate: 8 October 2024
  openingmonth: October
  deadlinedate: 16 September 2025
  deadlinetime: 6pm
  providerdeadline: 24 September 2025
  