salaries_date_appliesfrom: 1 September 2024

salaries:
# Summary salaries
  starting:
    min: £31,650
    minshortened: £31k
  fiveyears:
    max: £43,607
    maxshortened: £43k
  average:
    classroomshortened: £46k
# Detailed salaries
  qualifiedteacher:
    englandmin: £31,650
    englandmax: £49,084
    englandmaxshortened: £49k
    londonfringemin: £33,075
    londonfringemax: £50,471
    outerlondonmin: £36,413
    outerlondonmax: £53,994
    innerlondonmin: £38,766
    innerlondonmax: £60,092
  leadingpractitioner:
    englandmin: £50,025
    englandmax: £76,050
    londonfringemin: £51,403
    londonfringemax: £77,430
    outerlondonmin: £53,994
    outerlondonmax: £80,022
    innerlondonmin: £59,478
    innerlondonmax: £85,509
  headteacher:
    minshortened: £56k
    maxshortened: £147k
    englandmin: £56,316
    englandmax: £138,265
    londonfringemin: £57,693
    londonfringemax: £139,632
    outerlondonmin: £60,266
    outerlondonmax: £142,178
    innerlondonmin: £65,731
    innerlondonmax: £147,586
  unqualifiedteacher:
    englandmin: £21,731
    englandmax: £33,902
    londonfringemin: £23,140
    londonfringemax: £35,305
    outerlondonmin: £25,758
    outerlondonmax: £37,932
    innerlondonmin: £27,252
    innerlondonmax: £39,417
# Additional payments
  tlr:
    max: £16,553
# Example variables - used in documentation
  example:
    min: £30,000
salaries_example_max: £41k
