salaries_date_appliesfrom: 1 September 2026

salaries:
# Summary salaries
  starting:
    min: £34,000
    minshortened: £34k
  fiveyears:
    max: £46,960
    maxshortened: £46k
  average:
    classroomshortened: £52k
# Detailed salaries
  qualifiedteacher:
    englandmin: £34,069
    englandmax: £52,835
    englandmaxshortened: £52k
    londonfringemin: £35,602
    londonfringemax: £54,328
    outerlondonmin: £39,196
    outerlondonmax: £58,120
    innerlondonmin: £41,729
    innerlondonmax: £64,684
  leadingpractitioner:
    englandmin: £53,847
    englandmax: £81,861
    londonfringemin: £55,332
    londonfringemax: £83,347
    outerlondonmin: £58,120
    outerlondonmax: £86,136
    innerlondonmin: £64,024
    innerlondonmax: £92,043
  headteacher:
    minshortened: £60k
    maxshortened: £148k
    englandmin: £60,619
    englandmax: £148,829
    londonfringemin: £62,102
    londonfringemax: £150,301
    outerlondonmin: £64,871
    outerlondonmax: £153,042
    innerlondonmin: £70,754
    innerlondonmax: £158,863
  unqualifiedteacher:
    englandmin: £23,732
    englandmax: £36,494
    londonfringemin: £24,909
    londonfringemax: £38,004
    outerlondonmin: £27,727
    outerlondonmax: £40,831
    innerlondonmin: £29,336
    innerlondonmax: £42,429
# Additional payments
  tlr:
    max: £17,819
