salaries_date_appliesfrom: 1 September 2025

salaries:
# Summary salaries
  starting:
    min: £32,916
    minshortened: £32.9k
  fiveyears:
    max: £45,352
    maxshortened: £45k
  average:
    classroomshortened: £46k
# Detailed salaries
  qualifiedteacher:
    englandmin: £32,916
    englandmax: £51,048
    englandmaxshortened: £51k
    londonfringemin: £34,398
    londonfringemax: £52,490
    outerlondonmin: £37,870
    outerlondonmax: £56,154
    innerlondonmin: £40,317
    innerlondonmax: £62,496
  leadingpractitioner:
    englandmin: £52,026
    englandmax: £79,092
    londonfringemin: £53,460
    londonfringemax: £80,528
    outerlondonmin: £56,154
    outerlondonmax: £83,223
    innerlondonmin: £61,858
    innerlondonmax: £88,930
  headteacher:
    minshortened: £58k
    maxshortened: £153k
    englandmin: £58,569
    englandmax: £143,796
    londonfringemin: £60,001
    londonfringemax: £145,218
    outerlondonmin: £62,677
    outerlondonmax: £147,866
    innerlondonmin: £68,361
    innerlondonmax: £153,490
  unqualifiedteacher:
    englandmin: £22,601
    englandmax: £35,259
    londonfringemin: £24,066
    londonfringemax: £36,718
    outerlondonmin: £26,789
    outerlondonmax: £39,450
    innerlondonmin: £28,343
    innerlondonmax: £40,994
# Additional payments
  tlr:
    max: £17,216