scholarships:
  chemistry: £30,000
  computing: £30,000
  languagesfrenchgermanspanish: £27,000
  maths: £30,000
  physics: £30,000
  generic:
    max: £30,000
    maxshortened: £30k
  nonuk:
    max: £30,000