desc "Code Coverage tasks"
namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task collate: :environment do
    require "simplecov"
    require "simplecov_json_formatter"

    SimpleCov.collate Dir["#{ENV['COVERAGE_DIR']}/**/.resultset.json"], "rails" do
      formatter SimpleCov::Formatter::MultiFormatter.new([
        SimpleCov::Formatter::HTMLFormatter,
        SimpleCov::Formatter::JSONFormatter,
      ])
    end
  end
end
