  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          Get Into Teaching Application and Content 
  DOCKER_REPOSITORY:     ghcr.io/dfe-digital/get-into-teaching-frontend
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Get Into Teaching Application and Content
  REVIEW_APPLICATION:    review-get-into-teaching-app
  PAAS_APPLICATION_NAME: get-into-teaching-app
