  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          Get Into Teaching Application
  DOCKERHUB_REPOSITORY:  dfedigital/get-into-teaching-web
  CONTENT_REPOSITORY:    DFE-Digital/get-into-teaching-content
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Get Into Teaching Application
