inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - Rakefile
    - config.ru
    - db/schema.rb
    - bin/*
    - node_modules/**/*


Lint/AmbiguousOperator:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/**/*steps_controller.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - rolling
    - preprod
    - userresearch
    - production
