inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - rolling
    - preprod
    - userresearch
    - production

Lint/AmbiguousOperator:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/**/*steps_controller.rb'
