inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - Rakefile
    - config.ru
    - db/schema.rb
    - bin/*
    - node_modules/**/*

Lint/AmbiguousOperator:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/**/*steps_controller.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - rolling
    - preprod
    - userresearch
    - production

RSpec/AnyInstance:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false
