---
inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - Rakefile
    - config.ru
    - db/schema.rb
    - bin/*
    - node_modules/**/*
    - spec/models/wizard/**/*  # Separate PR splits this out into gem

RSpec/Capybara/FeatureMethods:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/**/*steps_controller.rb'

Naming/MethodParameterName:
  Exclude:
    - 'app/components/arrow_component.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - rolling
    - preprod
    - production
    - pagespeed

RSpec/AnyInstance:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/ClassVars:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - spec/requests/redirects_spec.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/features/content_pages_spec.rb
    - spec/requests/redirects_spec.rb

RSpec/NamedSubject:
  Exclude:
    - spec/**/*.rb

RSpec/SubjectStub:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Exclude:
    - spec/**/*.rb

RSpec/MessageSpies:
  Exclude:
    - spec/**/*.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*.rb

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Max: 15

Rails/SaveBang:
  Exclude:
    - spec/**/*.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: never
