language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
addons:
  postgresql: "9.6"
install:
  - bundle install
  - nvm install 12.13.1
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  #- bundle exec rake db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rails webpacker:compile
  - bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: ADDYDfOGlYQOr7trnmq1xbShIuGvDCJ1jscMbm4VoXgQ9LUPb3powuFrsMBSoNU7PaC0Mgxzf2UaTJT5+JBwz4yjVs7YgQV602CmWP367PBw0nXZHK9JYwsIWpJntDK/UnBxhYa4ewQESZc4LI6NK9qwOcITrzUoL8JDNPeAFo2+WTAFjPo9VigAIju4EMOnFagHt0Ay6Vt40kAGEpyeWfVj60ARYX8HHTnNF2oFIVDD9ZDa9QbeL/J6JqTUR/+qk4ivtNjnWjq9OiPfSeMR6pYaH4BNEC4qTq6ZtmadvGgWO7VgwGiQ0sz+v6rOKlrszQipYESZTmiwjByWK9iOrxul1DP9rWgqoY8WM9aTc3cZqZkUXH4hyFCki2go6/Cb2c0/+du8eMmDjp+J2Xi3B1H6DW+g0KdDqWqu/qni3Ndm2GNeJRZNdLgGNM23izWiPu/AlT2Bk/vMuEtVw2qgpwt3P6YSn95jqq88aTuS4hOU/Aq3mUm+w+TNpmglxkWtXUstghiNCHNw/cm3us/nuuq0OZPFMLt1Hg6R7FWFygnw7q1dfdt9hnw+oPEriIsJcNK0Kz1ISSsvefZfKfdyX6khgSCFdqZ5P8pCFHdIUKDUykdAcl27Phc2o4iCvo1Hn2AYzbQzv/1ONRcSd9D6qqnXVkufBpZ6CG/Q/AoILpc=
  app: govuk-rails-boilerplate
  on:
    repo: DFE-Digital/govuk-rails-boilerplate
