paas_space="get-into-teaching-test"
paas_app_application_name="get-into-teaching-app-test"
paas_app_route_name="get-into-teaching-app-test"
paas_additional_route_name="beta-getintoteaching"
paas_logging_endpoint_port="syslog-tls://89d7be0f-ddcd-437e-ad3c-c8125d0bad00-ls.logit.io:18190"
