paas_space="get-into-teaching-test"
paas_app_application_name="get-into-teaching-app-test"
paas_app_route_name="get-into-teaching-app-test"
paas_redis_1_name=  "get-into-teaching-app-test-redis-svc"
paas_additional_route_name="beta-getintoteaching"
