Date::DATE_FORMATS[:govuk] = "%d %B %Y"
Date::DATE_FORMATS[:default] = "%d %B %Y"
Date::DATE_FORMATS[:yearmonth] = "%Y-%m"
Date::DATE_FORMATS[:humanmonthyear] = "%B %Y"
Date::DATE_FORMATS[:long] = "%-d %B %Y"
Time::DATE_FORMATS[:full] = "%-d %B %Y %H:%M"
Time::DATE_FORMATS[:time] = "%H:%M"
