# Any paths listed here will have the Google Optimize code
# rendered on (it is disabled everywhere by default).
# For example:
#
# paths:
#   - /events
#   - /

paths:
  - /steps-to-become-a-teacher-search
  - /funding-and-support/scholarships-and-bursaries-search
  - /train-to-be-a-teacher/if-you-have-a-degree-search
  - /landing/train-to-teach-if-you-have-a-degree
  - /mailinglist/signup/name
  - /mailinglist/signup
  - /landing/how-to-fund-your-teacher-training
