# Any paths listed here will have the Google Optimize code
# rendered on (it is disabled everywhere by default).
# For example:
#
# paths:
#   - /events
#   - /

paths:
  - /landing/train-to-teach
  - /train-to-be-a-teacher
  - /landing/how-to-become-a-teacher
  - /landing/how-to-become-a-teacher-mailing-list
  - /teacher-training-adviser/sign_up/identity
  - /train-to-teach-if-you-have-a-degree
