# Any paths listed here will have the Google Optimize code
# rendered on (it is disabled everywhere by default).
# For example:
#
# paths:
#   - /events
#   - /

paths:
  - /salaries-and-benefits-search
  - /salaries-and-benefits-social
  - /landing/how-much-do-teachers-get-paid
  - /landing/how-much-do-teachers-get-paid-social
