routes:
  - title: Assessment only route
    course_length: Up to 12 weeks
    course_fee: "Yes"
    funding: "No"
    description: If you do not have qualified teacher status (QTS), but have worked as a teacher in 2 or more schools in England or overseas, you may be able to get QTS through the assessment only route. With this route, you do not need to do any further training. Instead, you’ll undertake a series of assessments. This may include lesson observations, providing a portfolio of evidence to show you meet the teachers’ standards, or written assessments.
    cta_text: Find out more about the assessment only route
    cta_link: /train-to-be-a-teacher/assessment-only-route-to-qts
    matches:
      - question: undergraduate_degree
        answers: ["Yes", "Not yet"]
      - question: unqualified_teacher
        answers: ["Yes"]
      - question: location
        answers: ["*"]

  - title: Postgraduate initial teacher training with fees
    course_length: 9 months full-time or up to 2 years part-time
    course_fee: "Yes"
    funding: Bursaries or scholarships, as well as student loans, are available if you’re eligible
    description: These courses combine theoretical learning with at least 2 classroom placements in schools. During your course, you’ll get the experience and knowledge you need to get qualified teacher status (QTS). On some courses, you can combine QTS with a postgraduate certificate in education (PGCE).
    cta_text: Find out more about postgraduate teacher training with fees
    cta_link: /train-to-be-a-teacher/if-you-have-a-degree
    matches:
      - question: undergraduate_degree
        answers: ["Yes", "Not yet"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["*"]
    highlight:
      text: "Most popular route"
      matches:
        - question: undergraduate_degree
          answers: ["Yes"]
        - question: unqualified_teacher
          answers: ["No"]
        - question: location
          answers: ["*"]

  - title: Postgraduate initial teacher training with a salary
    course_length: 9 to 12 months
    course_fee: Varies
    funding: "No"
    description: These courses allow you to earn a salary while you train towards qualified teacher status (QTS). You’ll still do some theoretical learning, but most of your time will be spent in school placements. Salaried courses are in high demand and very competitive, and training providers may want you to have significant teaching or school experience. Courses include School Direct salaried and postgraduate teaching apprenticeships (PGTA). Some salaried courses may also come with fees.
    cta_text: Find out more about postgraduate teacher training with a salary
    cta_link: /funding-and-support/salaried-teacher-training
    matches:
      - question: undergraduate_degree
        answers: ["Yes", "Not yet"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["*"]

  - title: Teach First (high potential initial teacher training)
    course_length: 24 months
    course_fee: "No"
    funding: "No"
    description: Teach First is a charitable organisation that currently delivers high potential initial teacher training, an employment-based route into teaching for high performing graduates and career changers. You’ll earn a salary while working towards qualified teacher status (QTS) with a postgraduate certificate in education (PGCE).
    cta_text: Find out more on the Teach First website
    cta_link: "https://www.teachfirst.org.uk"
    matches:
      - question: undergraduate_degree
        answers: ["Yes", "Not yet"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["*"]

  - title: Undergraduate initial teacher training
    course_length: 3 to 4 years
    course_fee: "Yes"
    funding: Student loans and bursaries are available, if you're eligible
    description: With these courses, you'll train to be a teacher as part of your bachelor's degree and get qualified teacher status (QTS). Qualifications vary depending on the course. For example, you could get QTS with a Bachelor of Arts (BA), Bachelor of Education (BEd), or Bachelor of Science (BSc).
    cta_text: Find out more about undergraduate initial teacher training
    cta_link: /train-to-be-a-teacher/if-you-dont-have-a-degree
    matches:
      - question: undergraduate_degree
        answers: ["No"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["*"]

  - title: International qualified teacher status (iQTS)
    course_length: 9 months full-time or up to 2 years part-time
    course_fee: "Yes"
    funding: "No"
    description: iQTS is a teaching qualification backed by the UK government. You can train where you live and work, with no need to visit the UK. iQTS meets the same high standards as English qualified teacher status (QTS) and leads to the automatic award of QTS.
    cta_text: Find out more about iQTS
    cta_link: /non-uk-teachers/international-qualified-teacher-status
    matches:
      - question: undergraduate_degree
        answers: ["Yes", "Not yet"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["No"]
    highlight:
      text: "Outside England"
      matches:
        - question: undergraduate_degree
          answers: ["Yes"]
        - question: unqualified_teacher
          answers: ["*"]
        - question: location
          answers: ["*"]

  - title: Teacher degree apprenticeship
    course_length: 4 years
    course_fee: "No"
    funding: "No"
    description: The teacher degree apprenticeship (TDA) is a teacher training programme where you’ll work in a school and earn a salary while getting a bachelor’s degree and qualified teacher status (QTS). The teacher training providers confirmed so far offer TDAs in secondary maths. TDAs in other subjects will be added throughout the year, up until September 2025, with training due to start in autumn 2025.
    cta_text: Find out more about teacher degree apprenticeships
    cta_link: /train-to-be-a-teacher/teacher-degree-apprenticeships
    matches:
      - question: undergraduate_degree
        answers: ["No"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["*"]

  - title: Undergraduate degree (followed by postgraduate teacher training)
    course_length: Varies
    course_fee: Varies
    funding: Varies
    description: Complete an undergraduate degree in a subject you’re passionate about. Then complete postgraduate initial teacher training to gain qualified teacher status (QTS) so you can share your expertise with pupils and inspire them to learn. This option gives you the flexibility to explore a subject you love, and time to decide whether you want to teach primary or secondary.
    cta_text: Find out more about undergraduate degree followed by postgraduate teacher training
    cta_link: /train-to-be-a-teacher/if-you-have-a-degree
    matches:
      - question: undergraduate_degree
        answers: ["No"]
      - question: unqualified_teacher
        answers: ["*"]
      - question: location
        answers: ["*"]
