name: Clean up Azure Storage Account

on:
  workflow_dispatch:
  schedule: # Midnight every day
    - cron: '0 0 * * *'

jobs:
  clean-azure:
    runs-on: ubuntu-latest
    environment:
          Development
          
    steps:
      - name: Install Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli  
          
      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DFE-Digital/github-actions/keyvault-yaml-secret@master
        id: PAAS-USERNAME
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          yaml_secret: INFRA-KEYS
          secret: PAAS-USERNAME

      - uses: DFE-Digital/github-actions/keyvault-yaml-secret@master
        id: PAAS-PASSWORD
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          yaml_secret: INFRA-KEYS
          secret: PAAS-PASSWORD

      - name: Login to Cloud Foundry
        run: cf login -a api.london.cloud.service.gov.uk -u ${{steps.PAAS-USERNAME.outputs.secret-value}} -p ${{steps.PAAS-PASSWORD.outputs.secret-value}} -s get-into-teaching 

      - name: Remove old Review Terraform Files
        run:  |
            cf target -s get-into-teaching
            BLOBS=$(az storage blob list -o json --container-name pass-tfstate --account-key ${{secrets.ARM_ACCESS_KEY}} --account-name s146d01sgtfstate  | jq -r '.[] | select(.name | contains( "review-get-into-teaching-app-")) | .name' )
            APPS=$(cf apps | cut -d ' ' -f1 | grep 'review')

            for i in $(echo $BLOBS)
            do
                name=$(echo $i |  cut -f1  -d '.' )
                if ! [[ $APPS =~ (^|[[:space:]])"$name"($|[[:space:]]) ]] ; then
                     echo "....." $name
                     az storage blob delete --container-name  pass-tfstate --account-name s146d01sgtfstate --account-key ${{secrets.ARM_ACCESS_KEY}} -n ${i}
                fi
            done
