
name: Run CVE scanner 
on:
  workflow_dispatch:

jobs:
  cve:
    name: CVE scanner 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - name: Install Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli  
          
      - name: Login to Cloud Foundry
        run: cf login -a api.london.cloud.service.gov.uk -u ${{secrets.GOVUKPAAS_USERNAME}} -p ${{secrets.GOVUKPAAS_PASSWORD}} -s get-into-teaching-monitoring
             
      
      - name: Set Env
        run: |
            cf set-env STEVE BUILD_CONTENT_TOKEN '${{secrets.BUILD_CONTENT_TOKEN}}'
      
      - name: Give me 2 minutes
        run:  sleep 120
        
      - name: Drop Image
        run:  cf delete STEVE -r -f


