name: Run CVE scanner 
on:
  workflow_dispatch:

env:
  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com/DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          Get Into Teaching Application
  DOCKERHUB_REPOSITORY:  dfedigital/get-into-teaching-web
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Get Into Teaching Application (code)
  
jobs:
  cve:
    name: CVE scanner 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1.1
        id:   azSecret
        with:
           keyvault: ${{ secrets.KEY_VAULT}}
           secrets: 'SLACK-WEBHOOK'

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Scan image
        uses: anchore/scan-action@v2
        with:
             image:  localbuild/testimage:latest
             fail-build: true
             severity-cutoff: high
             acs-report-enable: true

      - name: upload Anchore scan SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_COLOR: ${{ env.SLACK_ERROR}}
           SLACK_MESSAGE: 'The Application CVE Workflow has failed'
           SLACK_TITLE: 'Application CVE Workflow failure'
           SLACK_WEBHOOK: ${{ steps.azSecret.outputs.SLACK-WEBHOOK }}


