name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "45 3 * * *"

permissions:
  contents: write
  id-token: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # Pinned at v2.8.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --max-retries 20 app/views/content
          fail: true

      - name: Read Lychee output into var
        id: lychee-output
        if: ${{steps.lychee.outcome}} == "failure"
        run: |
          DATA=$(cat  ./lychee/out.md)
          echo "LYCHEE_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$DATA" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # - name: Slack Markdown Converter
      #   id: convert
      #   if: ${{steps.lychee.outcome}} == "failure"
      #   uses: LoveToKnow/slackify-markdown-action@698a1d4d0ff1794152a93c03ee8ca5e03a310d4e # Pinned at v1.1.1
      #   with:
      #     text: |
      #           ${{ env.LYCHEE_OUTPUT }}

      - name: Notify teams channel on job failure
        if: ${{steps.lychee.outcome}} == "failure"
        uses: DFE-Digital/github-actions/send-to-teams-channel@master
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'External link check results:'
          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
          message: |
            ${{ env.LYCHEE_OUTPUT  }}
