name: Run PageSpeed task
on:
  schedule:
    - cron:  '0 8 * * *' # 8am daily
  workflow_dispatch:

jobs:
  cf:
    name: Cloud Foundry Network
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1
        id:   azSecret
        with:
           keyvault: ${{ secrets.KEY_VAULT}}
           secrets: 'PAAS-USERNAME, PAAS-PASSWORD'

      - name: Login to Cloud Foundry
        run: cf login -a api.london.cloud.service.gov.uk -u ${{steps.azSecret.outputs.PAAS-USERNAME}} -p ${{steps.azSecret.outputs.PAAS-PASSWORD}} -s get-into-teaching

      - name: Reboot PageSpeed instance
        run:  |
            cf target -s get-into-teaching-test
            cf restage get-into-teaching-app-page-speed
