name: Run PageSpeed task
on:
  schedule:
    - cron:  '0 8 * * *' # 8am daily
  workflow_dispatch:

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1.2
      id: azSecret
      with:
          keyvault: ${{ secrets.KEY_VAULT }}
          secrets: 'HTTP-USERNAME, HTTP-PASSWORD'
    - name: Run Page Speed Tas
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://get-into-teaching-app-pagespeed.london.cloudapps.digital/pagespeed/run'
        method: 'POST'
        username: ${{ secrets.HTTP-USERNAME }}
        password: ${{ secrets.HTTP-PASSWORD }}
        timeout: 3600000 # 1hr in ms
