name: Run PageSpeed task
on:
  workflow_dispatch:

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
    - name: Run Page Speed
      uses: fjogeleit/http-request-action@fd5cf60c69049efb1397207cc8b442709a869685
      with:
        url: https://get-into-teaching-app-pagespeed.london.cloudapps.digital/pagespeed/run
        method: POST
        timeout: 3600000 # 1hr in ms
        preventFailureOnNoResponse: true
