name: Run PageSpeed task
on:
  schedule:
    - cron:  '0 8 * * *' # 8am daily
  workflow_dispatch:

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
    - name: Run Page Speed
      uses: fjogeleit/http-request-action@4ae1dfba856bfb530598ebb818f204befbb24cda
      with:
        url: https://get-into-teaching-app-pagespeed.london.cloudapps.digital/pagespeed/run
        method: POST
        timeout: 3600000 # 1hr in ms
        preventFailureOnNoResponse: true
