name: Nightly Snyk Security Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'  # 5:30am daily

permissions:
  contents: write
  id-token: write

jobs:
  security_tests:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # Pinned at v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image:  ${{ env.DOCKER_REPOSITORY }}:master
          args: --severity-threshold=high --file=Dockerfile --exclude-app-vulns

      - name: Run Brakeman static security scanner
        run: |-
          docker run -t --rm -e RAILS_ENV=test ${{ env.DOCKER_REPOSITORY }}:master brakeman --no-pager

      - name: Notify teams channel on job failure
        if: failure()
        uses: DFE-Digital/github-actions/send-to-teams-channel@master
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Nightly security scan
          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
          message: |
            Failure with security scan
